spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likelion
    username: root
    password: 1113

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
