spring:
  datasource:
    url: jdbc:mysql://likelion-database.c9qy0akgsvnw.ap-northeast-2.rds.amazonaws.com:3306/team2
    username: likelion
    password: likelion1234


  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
